### ISSUE TITLE
No VideoStream and Audio Stream Found

### ISSUE THREAD

**Issue by nikulvaghasiya** [kotvertolet/youtube-jextractor#14]
No Video Stream and Audio Stream Found
youtube extractor not working
plase update your repo.

thanks..

**Comment by kotvertolet** [comment]
@nikulvaghasiya working on it, thaks for notifying me

**Comment by kotvertolet** [comment]
duplicates #13

**Comment by kotvertolet** [comment]
Duplicates #13
