### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by captain-nemo1** [kotvertolet/youtube-jextractor#16]
videoData = youtubeJExtractor.extract() 
When ever i call this with a videoid it gives me this error.

https://del.dog/wuxinanebo.txt

I am using 0.2.0 
I saw similiar issue earlier which were fixed but I am still getting it.
Let me know if the problem is from my side.

**Comment by kotvertolet** [comment]
@captain-nemo1 Looks like the problem is on your side because I can't reproduce it with my unit tests. If you still facing this issue please provide more info about it and I'll try to help you.

**Comment by lorenzo-geromel** [comment]
I'm actually facing the same issue, apparently with any video.
So far I've tried with:
- https://www.youtube.com/watch?v=rhKm-H8Cb7k
- https://www.youtube.com/watch?v=0gizLT97cKo
- https://www.youtube.com/watch?v=gsN4tNMdDCs

And all of them results in the same NullPointerException @captain-nemo1 pointed out.

**Comment by kotvertolet** [comment]
@lorenzo-geromel What laguage level your app is using?

**Comment by lorenzo-geromel** [comment]
Do you mean the Java version? If so, 1.8 (Java 8)

**Comment by kotvertolet** [comment]
@lorenzo-geromel Thanks for your help, I've reproduced this problem. Still trying to find what causes it.

**Comment by captain-nemo1** [comment]
@kotvertolet Sorry for late reply. But I think you have caught the problem. Does this only happen with Java 8?

**Comment by captain-nemo1** [comment]
@kotvertolet   Sorry for the late reply. If you need any help or logs just let me know

**Comment by kotvertolet** [comment]
@captain-nemo1 Thanks, I appriciate that, but for now I have everything I need. This problem is very strange and I spent quite some time trying to find out why it occurs but still no luck.

**Comment by kotvertolet** [comment]
@captain-nemo1 
@lorenzo-geromel 
Fixed, check release 0.2.3. It was tough, btw. I spent lots of time trying to find out why it throws NPE when library is added as dependency and works totally fine when I run tests or when I add it into project as module. It turned out that the whole deal was in this line: 
`minifyEnabled true`

**Comment by captain-nemo1** [comment]
@kotvertolet Its working fine now. Thanks for your work. And I don't know where you live but Stay safe from Corona.
