### ISSUE TITLE
No stream data for audio+video 

### ISSUE THREAD

**Issue by comptoost** [kotvertolet/youtube-jextractor#19]
Hi, you have created very good git
but i am not getting links for iTag 18,34,35,59,78,22,37,38
with getVideoStreamItems i get video_only links which does not contain any audio
please update getVideoStreamItems it or create a new method to get this iTags

**Comment by kotvertolet** [comment]
@comptoost getVideoStreamItems() should return only videos without audio, it is expected behaviour
If you need video with audio, you have to take both streams and then use something like [this ](https://developer.android.com/reference/android/media/MediaSync)

**Comment by comptoost** [comment]
thanks for response
so it is my suggestion to create method for this iTags
Thanks..

**Comment by comptoost** [comment]
hi after a huge searching i seen only this library can not get this iTags but other youtube extractors are getting links with itag 18 and 22
can you check it?

**Comment by kotvertolet** [comment]
@comptoost Availability of certain itags depends on the video itself, if streams with itag 18 and 22 are available for video my library should get them. Did you found a video that has streams with such itags but my lib doesn't extract them?

**Comment by comptoost** [comment]
yes almost every video has itag 18 or 22
i have switched to other library and it working well with same videos on which your one not work
here is example
https://www.youtube.com/watch?v=glaZwDDrTSo
https://www.youtube.com/watch?v=8QyDmvuts9s

**Comment by kotvertolet** [comment]
@comptoost  Okay, I will check. What library you're using now?

**Comment by comptoost** [comment]
https://github.com/naveedhassan913/YouTubeExtractor
Good Luck

**Comment by kotvertolet** [comment]
@comptoost Thanks mate, you was right, my lib was unable to extract non-adaptive streams (like itag 18, 22), but I've implemented this feature, it will be available in 0.2.5. Thanks for your suggestion!

**Comment by comptoost** [comment]
Superb congo
