### ISSUE TITLE
Url is null in AdaptiveVideoStream object

### ISSUE THREAD

**Issue by niteshfel** [kotvertolet/youtube-jextractor#22]
check for this video view-source :https://www.youtube.com/watch?v=1hl22MFBM6s
all generated URL is null ,  i found 8 formatted list from this method videoData.getStreamingData().getAdaptiveVideoStreams() , but in this all urls are null 
can you check this ASAP

**Comment by kotvertolet** [comment]
@niteshfel looking into it

**Comment by kotvertolet** [comment]
@niteshfel Fixed in 0.2.6, new version will be available as soon as build process will be finished at Jitpack

**Comment by niteshfel** [comment]
how can we use this module as a Gradle dependency

**Comment by kotvertolet** [comment]
@niteshfel you can refer to this [instruction](https://jitpack.io/#kotvertolet/youtube-jextractor)

**Comment by niteshfel** [comment]
Thanks Man
