### ISSUE TITLE
Live stream video have only one quality format 

### ISSUE THREAD

**Issue by niteshfel** [kotvertolet/youtube-jextractor#27]
In this method return only one format of live stream video videoData.getStreamingData().getHlsManifestUrl()

can you try for all supported format for live stream live 1080p, 720p, 480p formats

**Comment by kotvertolet** [comment]
@niteshfel In fact they already are, DASH and HLS streams are **adaptive**:
`Adaptive bitrate streaming is the ability to adjust video quality in the middle of a stream as network conditions change. Several streaming protocols, including MPEG-DASH, HLS, and HDS, allow for adaptive bitrate streaming.`

If you want to enforce quality level of the live stream, you have to do it through a code.

**Comment by niteshfel** [comment]
OKs Thanks
