### ISSUE TITLE
java.util.List.iterator()' on a null object reference

### ISSUE THREAD

**Issue by niteshfel** [kotvertolet/youtube-jextractor#28]
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

found exception when called 
videoData = youtubeJExtractor.extract(strings[0]);
you can check this url for extract : https://www.youtube.com/watch?v=w2iqOwRvaFY

**Comment by kotvertolet** [comment]
First check if strings array has length more than 0 in this case because
the exception you've got may be invoked by the empty array.

**Comment by niteshfel** [comment]
no . strings[0] have values then this error occur

**Comment by kotvertolet** [comment]
Please, provide the whole stacktrace then

**Comment by niteshfel** [comment]
An error occurred while executing doInBackground()

stackTrace = {StackTraceElement[8]@13841} 
  lineNumber = 1167
 7 = {StackTraceElement@13852} "java.lang.Thread.run(Thread.java:919)"
 5 = {StackTraceElement@13850} "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)"
  shadow$_monitor_ = 0
  methodName = "run"
  shadow$_monitor_ = 0
  lineNumber = 641
 1 = {StackTraceElement@13846} "java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)"
  fileName = "FutureTask.java"
  shadow$_monitor_ = 0
  shadow$_monitor_ = 0
 6 = {StackTraceElement@13851} "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)"
  shadow$_klass_ = {Class@6967} "class java.lang.StackTraceElement"
  fileName = "FutureTask.java"
 3 = {StackTraceElement@13848} "java.util.concurrent.FutureTask.run(FutureTask.java:271)"
  methodName = "run"
  fileName = "ThreadPoolExecutor.java"
  declaringClass = "android.os.AsyncTask$SerialExecutor$1"
  methodName = "setException"
 4 = {StackTraceElement@13849} "android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)"
  shadow$_klass_ = {Class@6967} "class java.lang.StackTraceElement"
  lineNumber = 383
  shadow$_klass_ = {Class@6967} "class java.lang.StackTraceElement"
  declaringClass = "android.os.AsyncTask$4"
  shadow$_klass_ = {Class@6967} "class java.lang.StackTraceElement"
  fileName = "Thread.java"
  methodName = "run"
  shadow$_monitor_ = 0
  declaringClass = "java.util.concurrent.ThreadPoolExecutor"
  declaringClass = "java.util.concurrent.FutureTask"
  shadow$_monitor_ = 0
  shadow$_klass_ = {Class@6967} "class java.lang.StackTraceElement"
  fileName = "AsyncTask.java"
  shadow$_klass_ = {Class@6967} "class java.lang.StackTraceElement"
  lineNumber = 399
  lineNumber = 252
  shadow$_monitor_ = 0
 2 = {StackTraceElement@13847} "java.util.concurrent.FutureTask.setException(FutureTask.java:252)"
  declaringClass = "java.lang.Thread"
  lineNumber = 271
  methodName = "runWorker"
  fileName = "ThreadPoolExecutor.java"
  methodName = "finishCompletion"
  fileName = "FutureTask.java"
  shadow$_klass_ = {Class@6967} "class java.lang.StackTraceElement"
  declaringClass = "java.util.concurrent.FutureTask"
  methodName = "run"
  declaringClass = "java.util.concurrent.ThreadPoolExecutor$Worker"
 0 = {StackTraceElement@13845} "android.os.AsyncTask$4.done(AsyncTask.java:399)"
  methodName = "done"
  declaringClass = "java.util.concurrent.FutureTask"
  lineNumber = 919
  shadow$_monitor_ = 0
  fileName = "AsyncTask.java"
  shadow$_klass_ = {Class@6967} "class java.lang.StackTraceElement"
  lineNumber = 289

**Comment by kotvertolet** [comment]
No, this will not help. Just make a screenshot of the stacktrace in
console. Is this error reproducible with any video or the specific ones?

**Comment by niteshfel** [comment]
Ok some videos found error not all video i will be share a screenshot 
you can check with video id : up0fWFqgC6g

![Capture_1](https://user-images.githubusercontent.com/61489276/83943708-dfc47900-a81b-11ea-8620-442a3797d05c.PNG)
![Capture_2](https://user-images.githubusercontent.com/61489276/83943714-e6eb8700-a81b-11ea-97f3-7958d982b4d3.PNG)

**Comment by kotvertolet** [comment]
@niteshfel I found what the problem is, I'll fix it ASAP.

**Comment by kotvertolet** [comment]
@niteshfel fixed, check 0.3.0 version

btw, thanks for the issues you're posting, it helps to improve the library a lot!

**Comment by niteshfel** [comment]
Your welcome man !
