### ISSUE TITLE
isLiveContent is true then only two formats are play 360 and 720

### ISSUE THREAD

**Issue by niteshfel** [kotvertolet/youtube-jextractor#32]
when videoData.getVideoDetails().isLiveContent() is true then get videoData.getStreamingData().getAdaptiveVideoStreams();

this video list have 10-15 video format urls like webm and mp4 but webm urls is not play in any player only mp4 urls are play for 360p and 720p  and this url is also play videoData.getStreamingData().getHlsManifestUrl() get by this method. so my question is can i get all working means playable urls from getStreamingData().getAdaptiveVideoStreams(); and both quality webm and mp4?

**Comment by kotvertolet** [comment]
@niteshfel 
>this video list have 10-15 video format urls like webm and mp4 but webm urls is not play in any player
This is not true, just copy the link and post it into the address bar of your browser, press enter and whoa!
