### ISSUE TITLE
Can you add subtitles(Captions) ?

### ISSUE THREAD

**Issue by abagaha** [kotvertolet/youtube-jextractor#37]
Hello, 
Can you add captions(Subtitle) support for this?

Below is subtitles example.
[Link](https://github.com/sealedtx/java-youtube-downloader/tree/master/src/main/java/com/github/kiulian/downloader/model/subtitles)

Can you copy the model to this project?

@kotvertolet

Also can you add method to get all video links from YouTube playlist?
So that method will return a list of video list in a youtube playlist?

Also when we take stream details, the size of a stream is null. The size property  is null. So Is this the expected behavior?

**Comment by kotvertolet** [comment]
@abagaha Thank you for suggestion I will definitely spend some time this weekend to implement it

**Comment by kotvertolet** [comment]
@abagaha Done. Could you please test version 0.3.2?
