### ISSUE TITLE
No Such Method Error when initialize  YoutubeVideoData

### ISSUE THREAD

**Issue by NguyenKhacPhuc** [kotvertolet/youtube-jextractor#41]
![image](https://user-images.githubusercontent.com/44175326/90272355-7ac67880-de87-11ea-8842-535edbc586e3.png)
I met this error when trying to intialize YoutubeVideoData, anyone can help please, and this is my main activity.
![image](https://user-images.githubusercontent.com/44175326/90272425-9af63780-de87-11ea-8caa-6ee44610dc00.png)

**Comment by kotvertolet** [comment]
@kotvertolet I will check, hold on

**Comment by NguyenKhacPhuc** [comment]
I tried to write those code lines in a new thread with excutors but the problem was remaining the same

**Comment by kotvertolet** [comment]
@NguyenKhacPhuc Nevertheless I can't reproduce your problem unfortunately
![1](https://i.ibb.co/RD5Y2Gv/image.png)
