### ISSUE TITLE
this video id return zero format can u plz check : Ov6s1AzcV7k

### ISSUE THREAD

**Issue by niteshfel** [kotvertolet/youtube-jextractor#43]
video id = Ov6s1AzcV7k

**Comment by kotvertolet** [comment]
@niteshfel Will check

**Comment by kotvertolet** [comment]
@niteshfel It's okay.
![](https://i.ibb.co/d6JZcgp/github.png)

Sometimes it happens for a newlt uploaded video - youtube need sometimes to decode video and prepare different formats

**Comment by niteshfel** [comment]
Thanks @kotvertolet
