### ISSUE TITLE
Wrong Extract

### ISSUE THREAD

**Issue by wingchunna** [kotvertolet/youtube-jextractor#45]
Hi Kotvertolet,

This is my link youtube https://www.youtube.com/watch?v=aAxakbF24uY
when i search by youtube api and extract, its can be play and like : 
https://www.youtube.com/watch?v=aAxakbF24uY&gl=US&has_verified=1&bpctr=9999999999
when i search not by youtube api and extract (search by user interface in youtube.com), its can not play and  like : 
https://www.youtube.com/watch?v=4&gl=US&has_verified=1&bpctr=9999999999
I dont know why has diference in 2 case with the link.
Thanks !

**Comment by kotvertolet** [comment]
@wingchunna I didn't get it how you managed to get this link - https://www.youtube.com/watch?v=4&gl=US&has_verified=1&bpctr=9999999999 ? It's definetly incorrect because most important parameter **v** (which stands for 'video id') equals 4, it shouldn't be like that

**Comment by wingchunna** [comment]
Dear kotvertolet
I have a problem with your library recently. Many youtube video can not be
extract. When I dump log on Catch, i saw the notice : "
YtbExtractor.exception.ExtractionException: No js video player url found".
Pls tell me, how to fix it.
Thank you !

**Comment by kotvertolet** [comment]
@wingchunna  check a new version 0.3.3, it should work now

**Comment by wingchunna** [comment]
Thank you so much !
