### ISSUE TITLE
Live Video Issue

### ISSUE THREAD

**Issue by NiteshMisra** [kotvertolet/youtube-jextractor#47]
Not able to rewind the live youtube video.

**Comment by kotvertolet** [comment]
@NiteshMisra how did you tried to achieve that?

**Comment by NiteshMisra** [comment]
I used hlsManifestUrl for playing live video on Exoplayer

**Comment by NiteshMisra** [comment]
Did you find any solution ??
I am not able to play live videos smoothly.....

**Comment by kotvertolet** [comment]
@NiteshMisra Sorry, I missed this. So the problem is that you cant rewind more than 15 sec backward because it stopps playing at all?

**Comment by NiteshMisra** [comment]
Yes I just want to play live video smoothly with forward, rewind, play and pause features in it.
