### ISSUE TITLE
AdaptiveFormatItem list was null or empty

### ISSUE THREAD

**Issue by wingchunna** [kotvertolet/youtube-jextractor#52]
Hi Kotvertolet
I've updated lastest version and change new method extract with callback. But some video i received fault log

YtbExtractor.exception.ExtractionException: Extraction failed. Please, report here: https://github.com/kotvertolet/youtube-jextractor/issues. Error details: AdaptiveFormatItem list was null or empty

Some video i have : 
YtbExtractor.exception.ExtractionException: Extraction failed. Please, report here: https://github.com/kotvertolet/youtube-jextractor/issues. Error details: No js video player url found
Pls tell me how to fix it !
Thank you !

**Comment by kotvertolet** [comment]
@wingchunna hi! check new 0.3.3 version, sorry for the delay, I was ill
