### ISSUE TITLE
Cannot extract youtube player config, videoId was: kcoisguyvEA

### ISSUE THREAD

**Issue by ki-erp** [kotvertolet/youtube-jextractor#56]
I m getting the following error please help ASAP

**com.github.kotvertolet.youtubejextractor.exception.ExtractionException: Extraction failed. Please, report here: https://github.com/kotvertolet/youtube-jextractor/issues. Error details: Cannot extract youtube player config, videoId was: kcoisguyvEA**

**Comment by tijot123** [comment]
For me also same problem for all videos

**Comment by kotvertolet** [comment]
Thanks for letting me know, I will fix it ASAP

**Comment by ki-erp** [comment]
Working now Thanks, Admin @kotvertolet

**Comment by harinikshan** [comment]
While I am testing on android 10 version devices I am getting proper videoData but while I am running on oreo level devices I am getting "Cannot extract youtube player config" exceptions.
I am using the 0.3.3 version.
please check the issue
