### ISSUE TITLE
Extraction failed. Please, report here: https://github.com/kotvertolet/youtube-jextractor/issues. Error details: Cannot extract youtube player config, videoId was: https://www.youtube.com/watch?v=rCoPr8UwRMc

### ISSUE THREAD

**Issue by ahmadbilal17040** [kotvertolet/youtube-jextractor#62]
@kotvertolet Hey Admin Hope you are doing Well 
please check this issue i am using android 10 Redmi note 8 device

**Comment by ahmadbilal17040** [comment]
Issue is in this method please investigate this issue i am getting result null That's why this is happening Thanks
![image](https://user-images.githubusercontent.com/49881068/108390425-7a41dc80-7232-11eb-8adf-c0d7adfd2782.png)

**Comment by antonyhaman** [comment]
@ahmadbilal17040 fixed
