### ISSUE TITLE
Lightweight JS interpreter

### ISSUE THREAD

**Issue by betax96** [kotvertolet/youtube-jextractor#7]
I suggest that you change the javascript interpreter, liquidcore works perfectly but using this library the applications weigh a lot just for the use of this library.

There are other options that work in android to interpret javascript like rhino or js-evaluator-for-android.

**Comment by kotvertolet** [comment]
Hi! Thanks for posting this. During the initial development I've tried a few alternatives to LiquidCore including [ js-evaluator-for-android](https://github.com/evgenyneu/js-evaluator-for-android) and Rhino (through this [project](https://github.com/F43nd1r/rhino-android)), and what I didn't like about them is that js-evaluator-for-android requires a Context object to work and rhino-android is looks like abandoned project (last commit was 2 years ago), but I've never compared performance and size of them, maybe I should investigate that.

**Comment by betax96** [comment]
I have tried Rhino and it works well, as far as js-evaluator-for-android is better to avoid it because it requires Context to work since it uses webview to execute the javascript code.

The Rhino project has not been abandoned has updates constantly.
https://github.com/mozilla/rhino

To use it on android this library is used
implementation 'org.mozilla: rhino: 1.7.11'

and

Context rhino = Context.enter ();
         rhino.setOptimizationLevel (-1);

to be compatible with android

**Comment by kotvertolet** [comment]
Thanks for your clarification, I've replaced LiquidCore with Rhino successfully. In fact, I can't see any significant difference in terms of performance, but overall aar size is a bit less (45KB vs 60KB) and it's good.
